name = "freefinder-referrals"
main = "src/index.js"
compatibility_date = "2026-03-09"

[[kv_namespaces]]
binding = "REFERRALS"
id = "a9e89926db014692adccdd2cf8272d2b"
preview_id = "a5e0b2f7311e42a2afde0b859f911a45"
